### ISSUE TITLE
ReferenceError: safeDump not defined

### ISSUE THREAD

**Issue by carodelafuente** [sumitoberoi1/ServerTheScoop#2]
https://github.com/sumitoberoi1/ServerTheScoop/blob/e52c4d43564ad884a2825868d3dc617fb7003f97/server.js#L378-L385

I get an error here, probably because you forgot to specify yaml before the safeDump method: `yaml.safeDump()`

**Comment by sumitoberoi1** [comment]
Thanks for the comment will look into this
